Repository SU-SWS/trustee_profile, pull requests merged in 2022-03, with the labels that each got.

#11 Updates from stanford_profile
  config/sync/core.extension.yml
  tests/codeception/acceptance/SubThemeCest.php
Labels: size/xs

#13 Updates from stanford_profile
  CHANGELOG.md
  config/sync/core.entity_form_display.taxonomy_term.cap_org_codes.default.yml
  config/sync/core.entity_form_display.taxonomy_term.event_audience.default.yml
  config/sync/core.entity_form_display.taxonomy_term.stanford_event_types.default.yml
  config/sync/core.entity_form_display.taxonomy_term.stanford_news_topics.default.yml
  config/sync/core.entity_form_display.taxonomy_term.stanford_person_types.default.yml
  config/sync/core.entity_form_display.taxonomy_term.stanford_publication_topics.default.yml
  config/sync/core.entity_view_display.node.stanford_event.default.yml
  config/sync/core.extension.yml
  config/sync/webp.settings.yml
  tests/codeception/acceptance/Content/BasicPageCest.php
Labels: size/s

#17 Updates from stanford_profile
  config/sync/core.entity_form_display.config_pages.lockup_settings.default.yml
  config/sync/core.entity_form_display.config_pages.stanford_local_footer.default.yml
  config/sync/core.entity_view_display.config_pages.lockup_settings.default.yml
  config/sync/core.entity_view_display.config_pages.stanford_local_footer.default.yml
  config/sync/core.extension.yml
  config/sync/field.field.config_pages.lockup_settings.su_intro.yml
  config/sync/field.field.config_pages.stanford_local_footer.su_local_foot_help.yml
  config/sync/field.storage.config_pages.su_intro.yml
  config/sync/field.storage.config_pages.su_local_foot_help.yml
  config/sync/filter.format.stanford_html.yml
  config/sync/ultimate_cron.job.core_event_dispatcher_cron.yml
Labels: size/m

#18 Updates from stanford_profile
  config/sync/core.entity_form_display.media.embeddable.default.yml
  config/sync/core.entity_form_display.media.embeddable.media_library.yml
  config/sync/core.entity_form_display.media.file.default.yml
  config/sync/core.entity_form_display.media.file.media_library.yml
  config/sync/core.entity_form_display.media.google_form.default.yml
  config/sync/core.entity_form_display.media.google_form.media_library.yml
  config/sync/core.entity_form_display.media.image.default.yml
  config/sync/core.entity_form_display.media.image.media_library.yml
  config/sync/core.entity_form_display.media.stanford_gallery_images.default.yml
  config/sync/core.entity_form_display.media.stanford_gallery_images.media_library.yml
  config/sync/core.entity_form_display.media.video.default.yml
  config/sync/core.entity_form_display.media.video.media_library.yml
  config/sync/core.entity_form_display.node.stanford_event.default.yml
  config/sync/core.entity_form_display.node.stanford_event_series.default.yml
  config/sync/core.entity_form_display.node.stanford_news.default.yml
  config/sync/core.entity_form_display.node.stanford_page.default.yml
  config/sync/core.entity_form_display.node.stanford_person.default.yml
  config/sync/core.entity_form_display.node.stanford_publication.default.yml
  config/sync/core.entity_form_display.taxonomy_term.cap_org_codes.default.yml
  config/sync/core.entity_form_display.taxonomy_term.event_audience.default.yml
  config/sync/core.entity_form_display.taxonomy_term.stanford_event_types.default.yml
  config/sync/core.entity_form_display.taxonomy_term.stanford_news_topics.default.yml
  config/sync/core.entity_form_display.taxonomy_term.stanford_person_types.default.yml
  config/sync/core.entity_form_display.taxonomy_term.stanford_publication_topics.default.yml
  config/sync/core.extension.yml
  config/sync/filter.format.stanford_html.yml
  config/sync/migrate_plus.migration.stanford_localist_importer.yml
Labels: size/s

#22 Switched upstream merge to main release branch from working dev branch.
  .circleci/config.yml
Labels: size/xs

#33 Updates from stanford_profile
  .circleci/config.yml
  .github/workflows/tag_commits_to_master.yml
  CHANGELOG.md
  README.md
  composer.json
  config/sync/block.block.minimally_branded_subtheme_branding.yml
  config/sync/block.block.minimally_branded_subtheme_config_pages.yml
  config/sync/block.block.minimally_branded_subtheme_config_pages_stanford_global_msg.yml
  config/sync/block.block.minimally_branded_subtheme_config_pages_stanford_super_footer.yml
  config/sync/block.block.minimally_branded_subtheme_content.yml
  config/sync/block.block.minimally_branded_subtheme_help.yml
  config/sync/block.block.minimally_branded_subtheme_local_tasks.yml
  config/sync/block.block.minimally_branded_subtheme_main_navigation.yml
  config/sync/block.block.minimally_branded_subtheme_messages.yml
  config/sync/block.block.minimally_branded_subtheme_pagetitle.yml
  config/sync/block.block.minimally_branded_subtheme_search.yml
  config/sync/block.block.minimally_branded_subtheme_search_form.yml
  config/sync/config_ignore.settings.yml
  config/sync/core.entity_form_display.config_pages.stanford_events_importer.default.yml
  config/sync/core.entity_view_display.node.stanford_event.default.yml
  config/sync/core.entity_view_display.node.stanford_event_series.default.yml
  config/sync/core.entity_view_display.node.stanford_news.default.yml
  config/sync/core.entity_view_display.node.stanford_page.default.yml
  config/sync/core.entity_view_display.node.stanford_person.default.yml
  config/sync/core.entity_view_display.node.stanford_publication.default.yml
  config/sync/core.extension.yml
  config/sync/field.field.config_pages.lockup_settings.su_lockup_options.yml
  config/sync/node.type.stanford_event.yml
  config/sync/views.view.content.yml
  tests/codeception/acceptance/Content/EventsCest.php
  tests/codeception/acceptance/Media/MediaPermissionsCest.php
  tests/codeception/acceptance/SubThemeCest.php
Labels: size/l

#30 BOT-27 - boosting max upload for files.
  config/sync/field.field.media.file.field_media_file.yml
  config/sync/field.storage.media.field_media_file.yml
Labels: size/xs
